// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for getting a metric
type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // counter or gauge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Response message for a metric
type MetricResponse struct {
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Delta         int64                  `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"`
	state         protoimpl.MessageState `protogen:"open.v1"`
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricResponse) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

// Request message for updating a metric
type MetricUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Delta         int64                  `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricUpdateRequest) Reset() {
	*x = MetricUpdateRequest{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricUpdateRequest) ProtoMessage() {}

func (x *MetricUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricUpdateRequest.ProtoReflect.Descriptor instead.
func (*MetricUpdateRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricUpdateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricUpdateRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricUpdateRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

// Request message for batch updating metrics
type BatchMetricUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricUpdateRequest `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMetricUpdateRequest) Reset() {
	*x = BatchMetricUpdateRequest{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMetricUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMetricUpdateRequest) ProtoMessage() {}

func (x *BatchMetricUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMetricUpdateRequest.ProtoReflect.Descriptor instead.
func (*BatchMetricUpdateRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *BatchMetricUpdateRequest) GetMetrics() []*MetricUpdateRequest {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Response message for batch updating metrics
type BatchMetricUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricResponse      `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMetricUpdateResponse) Reset() {
	*x = BatchMetricUpdateResponse{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMetricUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMetricUpdateResponse) ProtoMessage() {}

func (x *BatchMetricUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMetricUpdateResponse.ProtoReflect.Descriptor instead.
func (*BatchMetricUpdateResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *BatchMetricUpdateResponse) GetMetrics() []*MetricResponse {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\ametrics\"3\n" +
	"\rMetricRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"`\n" +
	"\x0eMetricResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\x03R\x05delta\"e\n" +
	"\x13MetricUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\x03R\x05delta\"R\n" +
	"\x18BatchMetricUpdateRequest\x126\n" +
	"\ametrics\x18\x01 \x03(\v2\x1c.metrics.MetricUpdateRequestR\ametrics\"N\n" +
	"\x19BatchMetricUpdateResponse\x121\n" +
	"\ametrics\x18\x01 \x03(\v2\x17.metrics.MetricResponseR\ametrics2\xf2\x01\n" +
	"\x0eMetricsService\x12<\n" +
	"\tGetMetric\x12\x16.metrics.MetricRequest\x1a\x17.metrics.MetricResponse\x12E\n" +
	"\fUpdateMetric\x12\x1c.metrics.MetricUpdateRequest\x1a\x17.metrics.MetricResponse\x12[\n" +
	"\x12BatchUpdateMetrics\x12!.metrics.BatchMetricUpdateRequest\x1a\".metrics.BatchMetricUpdateResponseB'Z%github.com/Nikolay961996/metsys/protob\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metrics_proto_goTypes = []any{
	(*MetricRequest)(nil),             // 0: metrics.MetricRequest
	(*MetricResponse)(nil),            // 1: metrics.MetricResponse
	(*MetricUpdateRequest)(nil),       // 2: metrics.MetricUpdateRequest
	(*BatchMetricUpdateRequest)(nil),  // 3: metrics.BatchMetricUpdateRequest
	(*BatchMetricUpdateResponse)(nil), // 4: metrics.BatchMetricUpdateResponse
}
var file_metrics_proto_depIdxs = []int32{
	2, // 0: metrics.BatchMetricUpdateRequest.metrics:type_name -> metrics.MetricUpdateRequest
	1, // 1: metrics.BatchMetricUpdateResponse.metrics:type_name -> metrics.MetricResponse
	0, // 2: metrics.MetricsService.GetMetric:input_type -> metrics.MetricRequest
	2, // 3: metrics.MetricsService.UpdateMetric:input_type -> metrics.MetricUpdateRequest
	3, // 4: metrics.MetricsService.BatchUpdateMetrics:input_type -> metrics.BatchMetricUpdateRequest
	1, // 5: metrics.MetricsService.GetMetric:output_type -> metrics.MetricResponse
	1, // 6: metrics.MetricsService.UpdateMetric:output_type -> metrics.MetricResponse
	4, // 7: metrics.MetricsService.BatchUpdateMetrics:output_type -> metrics.BatchMetricUpdateResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
